name = "qingping-wallpaper-api"
main = "wrangler/src/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "qingping-wallpaper-api"

[[env.production.d1_databases]]
binding = "DB"
database_name = "d1"
database_id = "633eb851-04f3-4a02-9b1e-6491e577c9d8"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "d3e6ffc9ae314ef89ec0c984999bd44b"

[env.development]
name = "qingping-wallpaper-api-dev"

[[env.development.d1_databases]]
binding = "DB"
database_name = "d1"
database_id = "633eb851-04f3-4a02-9b1e-6491e577c9d8"

[[env.development.kv_namespaces]]
binding = "CACHE"
id = "d3e6ffc9ae314ef89ec0c984999bd44b"

[vars]
API_VERSION = "2.0.0"
CORS_ORIGIN = "*"
ADMIN_TOKEN_EXPIRE = 604800